// Code Generated by Sidekick is for learning and experimentation purposes only.
@Library('jenkins-shared-libraryy') _

pipeline {
    agent any

    environment {
        S3_BUCKET = 'bucket-new-9164'
        S3_KEY    = 'myfunction.zip'
        REGION    = 'eu-north-1'
        LAMBDA_FUNCTION_NAME = 'my-lambda-func'
        ARTIFACT_PATH = 'build/myfunction.zip'
        ECS_CLUSTER_NAME = 'my-ecs-cluster'
        ECS_SERVICE_NAME = 'my-ecs-service'
        IMAGE = 'myrepo/myimage:latest'
        AWS_CREDENTIALS_ID = 'aws-creds' // reuse for both lambda/ECS
    }

    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
                sh 'ls -alR'
            }
        }

        stage('Build Lambda Artifact') {
            steps {
                sh 'mkdir -p build'
                sh 'zip -r build/myfunction.zip lambda_function_code/lambda_function.py'
                sh 'ls -lh build/'
            }
        }

        stage('Upload Lambda Artifact to S3') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: "${env.AWS_CREDENTIALS_ID}"]
                ]) {
                    sh '''
                        ls -lh build/myfunction.zip
                        aws s3 cp build/myfunction.zip s3://$S3_BUCKET/$S3_KEY --region $REGION
                    '''
                }
            }
        }

        stage('Lambda Deploy (shared lib)') {
            steps {
                script {
                    deployLambda(
                        functionName: env.LAMBDA_FUNCTION_NAME,
                        s3Bucket: env.S3_BUCKET,
                        s3Key: env.S3_KEY,
                        awsRegion: env.REGION,
                        awsCredentialsId: env.AWS_CREDENTIALS_ID
                    )
                }
            }
        }

        stage('Deploy to ECS (shared lib)') {
            steps {
                script {
                    deployECS(
                        cluster: env.ECS_CLUSTER_NAME,
                        service: env.ECS_SERVICE_NAME,
                        awsRegion: env.REGION,
                        awsCredentialsId: env.AWS_CREDENTIALS_ID
                    )
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully!'
        }
        failure {
            echo 'Deployment failed, please check earlier logs.'
        }
        always {
            cleanWs()
        }
    }
}
