// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any

    environment {
        S3_BUCKET = 'bucket-new-9164'                    // your S3 bucket name
        S3_KEY    = 'myfunction.zip'                     // object/key under the bucket
        REGION    = 'eu-north-1'                         // your AWS region
        LAMBDA_FUNCTION_NAME = 'my-lambda-func'          // your Lambda function name
    }

    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
                // Show repo contents for debugging
                sh 'ls -alR'
            }
        }

        stage('Build Lambda Artifact') {
            steps {
                script {
                    sh 'mkdir -p build'
                    // Adjust path as needed; assumes lambda_function.py is in right folder
                    sh 'zip -r build/myfunction.zip lambda_function_code/lambda_function.py'
                    sh 'ls -lh build/'
                }
            }
        }

        stage('Upload Lambda Artifact to S3') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    sh '''
                        ls -lh build/myfunction.zip
                        aws s3 cp build/myfunction.zip s3://$S3_BUCKET/$S3_KEY --region $REGION
                    '''
                }
            }
        }

        stage('Lambda Deploy') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    sh '''
                        echo "Updating Lambda function code from S3..."
                        aws lambda update-function-code \
                            --function-name $LAMBDA_FUNCTION_NAME \
                            --s3-bucket $S3_BUCKET \
                            --s3-key $S3_KEY \
                            --region $REGION
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully!'
        }
        failure {
            echo 'Deployment failed, please check earlier logs.'
        }
        always {
            cleanWs()
        }
    }
}
